apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: 127.0.0.1:9092
    - name: authType
      value: "none"
    - name: authRequired
      value: "false"